// @vitest-environment happy-dom
/**
 * Story 3.7 — Layer-2 JS-vs-SPICE attitude consistency gate.
 *
 * Runs the real production `AttitudeService.getBusQuat` / `getPlatformQuat`
 * (Story 3.2) against SpiceyPy ground-truth quaternions emitted by
 * `bake/src/l2_attitude_validation.py`. The fixture is generated by CI:
 *
 *   1. CI step "Generate L2 attitude fixture" runs the Python script,
 *      which writes `bake/out/l2-attitude-fixture.json` containing
 *      ≥ 500 random in-CK-coverage samples per spacecraft per window.
 *   2. CI step "Copy L2 fixture to web/public/data" copies the file to
 *      the location this test reads from.
 *   3. The default vitest collection picks up this file.
 *
 * Local-env contract (per Story 3.4 [3.4 / LOW] deferred-work item and
 * Story 3.7 § Local-env constraint):
 *   - `uv` / SpiceyPy may not be installed on the lead's machine; the
 *     fixture cannot be generated locally.
 *   - This test detects fixture absence via `fs.existsSync` at module top
 *     and `describe.skipIf(!fixturePresent)` the entire suite. Other tests
 *     in `cd web && npm test` continue to pass; the L2 assertion is then a
 *     CI-only gate.
 *
 * Comparison contract (per AC2 + ADR-0024 + NFR-P10):
 *   - `angularError = 2 * acos(min(1, |dot(q_js, q_truth)|))` — the
 *     absolute value of the dot product tolerates sign-flipped (but
 *     mathematically equivalent) quaternion answers, which can arise when
 *     the JS SLERP path's pre-bake-walked sign choice diverges from the
 *     SPICE-canonical sign at that knot.
 *   - The `Math.min(1, ...)` clamp guards against float overshoot at the
 *     `acos` input bounds when `q_js ≈ ±q_truth`.
 *   - Tolerance is 1 mrad (NFR-P10).
 *
 * Worst-case diagnosis: on failure, the assertion message reports the
 * spacecraftId / et / ckWindow / angularError of the worst sample, so the
 * CI log surfaces the offending instant directly without re-running the
 * fixture.
 */
import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { ChunkLoader } from '../src/services/chunk-loader';
import { EphemerisService } from '../src/services/ephemeris-service';
import { AttitudeService } from '../src/services/attitude-service';
import { ManifestLoader, __resetCacheForTests } from '../src/services/manifest-loader';
import type { Manifest, ManifestFile } from '../src/services/manifest-loader';

// === Fixture detection =====================================================

const REPO_ROOT = resolve(__dirname, '..', '..');
const FIXTURE_PATH = resolve(REPO_ROOT, 'web', 'public', 'data', 'l2-attitude-fixture.json');
const MANIFEST_PATH = resolve(REPO_ROOT, 'web', 'public', 'data', 'manifest.json');

const fixturePresent = existsSync(FIXTURE_PATH) && existsSync(MANIFEST_PATH);

// === Fixture record schema (mirrors `bake/src/l2_attitude_validation.py:L2Record`)

interface L2FixtureRecord {
  spacecraftId: number; // -31 or -32
  et: number;
  ckWindow: string;
  ground_truth_bus_quat: [number, number, number, number]; // scalar-last [x, y, z, w]
  ground_truth_platform_quat: [number, number, number, number];
}

// NFR-P10: max angle error ≤ 1 mrad (= 1e-3 rad).
const TOLERANCE_RAD = 1e-3;

// =============================================================================

describe.skipIf(!fixturePresent)(
  'Story 3.7 — L2 JS-vs-SPICE attitude consistency (NFR-P10 ≤ 1 mrad)',
  () => {
    /**
     * Build the boot stack:
     *   - Real `ChunkLoader` with a Node-side fetchImpl that reads
     *     `web/public/data/<file>` from disk (the same bytes Vite serves
     *     in dev, post-brotli-decompression, since `fs.readFileSync` reads
     *     the on-disk `.bin.br` raw whereas Vite serves them with
     *     `Content-Encoding: br`. The chunk-loader expects DECOMPRESSED
     *     bytes — see chunk-loader.ts:1-22 — so for our Node-side stub we
     *     decompress with brotli before returning).
     *   - Real `AttitudeService` constructed against the real manifest.
     *   - `EphemerisService` is constructed against the same chunkLoader
     *     but is never queried inside CK-coverage windows (every fixture
     *     ET is inside a CK window by construction in the fixture
     *     generator). A minimal stub satisfies the constructor without
     *     standing up ephemeris chunks.
     */
    const buildStack = async (
      manifest: Manifest,
    ): Promise<{
      chunkLoader: ChunkLoader;
      attitudeService: AttitudeService;
    }> => {
      const { brotliDecompressSync } = await import('node:zlib');

      const chunkLoader = new ChunkLoader({
        fetchImpl: (async (input: RequestInfo | URL) => {
          const raw = typeof input === 'string' ? input : input.toString();
          // chunk-loader anchors URLs at `${origin}/` (Story 3.3.1). Strip
          // the origin and leading slash to derive the on-disk path.
          let path = raw;
          if (raw.startsWith('http')) {
            try {
              path = new URL(raw).pathname.replace(/^\//, '');
            } catch {
              /* fall through with the raw value */
            }
          }
          // Manifest URLs look like `data/<file>.bin.br`. Anchor the
          // filesystem read under `web/public/`.
          const onDisk = resolve(REPO_ROOT, 'web', 'public', path);
          if (!existsSync(onDisk)) {
            return {
              ok: false,
              status: 404,
              statusText: 'Not Found',
              arrayBuffer: async () => new ArrayBuffer(0),
            } as Response;
          }
          const compressed = readFileSync(onDisk);
          const decompressed = brotliDecompressSync(compressed);
          const ab = decompressed.buffer.slice(
            decompressed.byteOffset,
            decompressed.byteOffset + decompressed.byteLength,
          ) as ArrayBuffer;
          return {
            ok: true,
            status: 200,
            statusText: 'OK',
            arrayBuffer: async () => ab,
          } as Response;
        }) as typeof fetch,
        // Skip on-the-fly integrity check — we trust the on-disk bytes
        // because they're the CI-generated artifact under test.
        sha256Hex: async () => 'unused',
      });

      // Minimal EphemerisService stub — never queried inside the CK window
      // path (the fixture's ETs are all inside CK coverage by
      // construction). The AttitudeService synthesized-path code is
      // guarded by a manifest lookup; for fixture ETs that lookup always
      // succeeds and we never reach the ephemeris query.
      const ephemerisStub = {
        getPosition: () => null,
        getVelocity: () => null,
        getStateAt: () => null,
      } as unknown as EphemerisService;

      const attitudeService = new AttitudeService(manifest, chunkLoader, ephemerisStub);

      return { chunkLoader, attitudeService };
    };

    const loadManifest = async (): Promise<Manifest> => {
      // Use the production ManifestLoader (with Zod validation) via a
      // Node-side fetch stub that reads the on-disk JSON. Keeps the parse
      // path identical to the runtime — drift between this test and
      // production would otherwise be invisible.
      __resetCacheForTests();
      const stubFetch = (async (_input: RequestInfo | URL) => {
        const json = readFileSync(MANIFEST_PATH, 'utf-8');
        return {
          ok: true,
          status: 200,
          statusText: 'OK',
          json: async () => JSON.parse(json),
        } as Response;
      }) as typeof fetch;
      return ManifestLoader.load('manifest.json', { fetchImpl: stubFetch });
    };

    const loadFixture = (): L2FixtureRecord[] => {
      const raw = readFileSync(FIXTURE_PATH, 'utf-8');
      const parsed = JSON.parse(raw);
      if (!Array.isArray(parsed)) {
        throw new Error(`L2 fixture is not a JSON array: ${FIXTURE_PATH}`);
      }
      return parsed as L2FixtureRecord[];
    };

    const angularErrorRad = (
      q_js: { x: number; y: number; z: number; w: number },
      q_truth: [number, number, number, number],
    ): number => {
      const [tx, ty, tz, tw] = q_truth;
      const dot = q_js.x * tx + q_js.y * ty + q_js.z * tz + q_js.w * tw;
      // ADR-0024 / Story 3.1: |dot| (absolute value) so sign-flipped but
      // mathematically equivalent quaternions don't spuriously fail.
      const clamped = Math.min(1, Math.abs(dot));
      return 2 * Math.acos(clamped);
    };

    /**
     * Prefetch every attitude chunk the fixture's ETs touch. The
     * AttitudeService's CK path is synchronous (returns null on cache
     * miss while kicking off the async load); rather than poll per
     * record we pre-warm the cache once so every getBusQuat /
     * getPlatformQuat call hits the cache synchronously and returns a
     * non-null answer.
     */
    const prefetchAttitudeChunks = async (
      manifest: Manifest,
      chunkLoader: ChunkLoader,
    ): Promise<void> => {
      const attitudeFiles: ManifestFile[] = [];
      for (const body of manifest.bodies) {
        for (const file of body.files) {
          if (file.kind === 'bus_attitude' || file.kind === 'platform_attitude') {
            attitudeFiles.push(file);
          }
        }
      }
      await Promise.all(attitudeFiles.map((f) => chunkLoader.load(f)));
    };

    it('every fixture record: JS quaternion matches SPICE ground truth within 1 mrad', async () => {
      const manifest = await loadManifest();
      const records = loadFixture();
      expect(records.length).toBeGreaterThan(0);

      const { chunkLoader, attitudeService } = await buildStack(manifest);
      await prefetchAttitudeChunks(manifest, chunkLoader);

      // Track the worst-case across all records for diagnostic emission.
      let worst = {
        kind: '',
        spacecraftId: 0,
        et: 0,
        ckWindow: '',
        angularError: 0,
      };
      let n_bus_compared = 0;
      let n_platform_compared = 0;
      let n_bus_null = 0;
      let n_platform_synthesized = 0;

      for (const record of records) {
        // Bus: always compared. The runtime SLERPs CK when available;
        // since every fixture record is inside a bus_attitude window
        // (by construction in `l2_attitude_validation.py`), the
        // provenance is 'ck' for every record.
        const busJs = attitudeService.getBusQuat(record.spacecraftId, record.et);
        if (busJs === null) {
          n_bus_null += 1;
        } else {
          const err = angularErrorRad(busJs, record.ground_truth_bus_quat);
          n_bus_compared += 1;
          if (err > worst.angularError) {
            worst = {
              kind: 'bus',
              spacecraftId: record.spacecraftId,
              et: record.et,
              ckWindow: record.ckWindow,
              angularError: err,
            };
          }
        }

        // Platform: compared ONLY when the runtime's provenance is 'ck'.
        // Story 3.1's `ck_sample._build_window_grid` does not emit
        // platform_attitude VTRJs for type-1 (discrete) CK records, so
        // the runtime falls back to the synthesized HGA-Earth-pointing
        // path for the scan platform — which is a regime entirely
        // separate from the SPICE ckgp ground truth. The L2 gate cannot
        // meaningfully assert synthesized-vs-CK; we record the count
        // and continue. The bus assertion is the load-bearing NFR-P10
        // gate of this fixture.
        const platformProvenance = attitudeService.getPlatformProvenance(
          record.spacecraftId,
          record.et,
        );
        if (platformProvenance === 'synthesized') {
          n_platform_synthesized += 1;
        } else {
          const platformJs = attitudeService.getPlatformQuat(
            record.spacecraftId,
            record.et,
          );
          if (platformJs === null) {
            // CK provenance but null result — chunk-load failed.
            n_platform_synthesized += 1;
          } else {
            const err = angularErrorRad(
              platformJs,
              record.ground_truth_platform_quat,
            );
            n_platform_compared += 1;
            if (err > worst.angularError) {
              worst = {
                kind: 'platform',
                spacecraftId: record.spacecraftId,
                et: record.et,
                ckWindow: record.ckWindow,
                angularError: err,
              };
            }
          }
        }
      }

      // After prefetch, every fixture ET should resolve to a non-null
      // bus quaternion — null returns indicate either a missing CK
      // chunk (prefetch failure) or a manifest/fixture drift.
      expect(
        n_bus_null,
        `${n_bus_null} bus quat lookups returned null after prefetch — ` +
          `manifest/fixture drift, or chunk load failed`,
      ).toBe(0);
      // Diagnostic: surface the platform compared / synthesized split.
      // Synthesized is acceptable (Story 3.1 platform-VTRJ gap); we
      // log it so a future fix to Story 3.1's `_build_window_grid` is
      // visibly recognized when the count drops to zero.
      // eslint-disable-next-line no-console
      console.info(
        `[L2] platform records: compared=${n_platform_compared}, ` +
          `synthesized-skip=${n_platform_synthesized} ` +
          `(synthesized-skip > 0 indicates Story 3.1 type-1-CK gap)`,
      );

      // The NFR-P10 gate.
      expect(
        worst.angularError,
        `worst-case L2 attitude error exceeds NFR-P10 1 mrad: ` +
          `kind=${worst.kind} spacecraftId=${worst.spacecraftId} ` +
          `et=${worst.et} ckWindow=${worst.ckWindow} ` +
          `angularError=${worst.angularError.toExponential(4)} rad ` +
          `(${(worst.angularError * 1000).toFixed(4)} mrad). ` +
          `Compared ${n_bus_compared} bus + ${n_platform_compared} platform records.`,
      ).toBeLessThanOrEqual(TOLERANCE_RAD);
    });

    it('fixture is sorted by (spacecraftId, et) — determinism contract from AC1', () => {
      const records = loadFixture();
      for (let i = 1; i < records.length; i++) {
        const prev = records[i - 1];
        const cur = records[i];
        const sortOk =
          cur.spacecraftId > prev.spacecraftId ||
          (cur.spacecraftId === prev.spacecraftId && cur.et >= prev.et);
        expect(
          sortOk,
          `fixture not sorted at index ${i}: prev=(${prev.spacecraftId}, ${prev.et}) ` +
            `cur=(${cur.spacecraftId}, ${cur.et})`,
        ).toBe(true);
      }
    });

    it('fixture quaternions are unit norm (sanity check on the Python emitter)', () => {
      const records = loadFixture();
      const TOL = 1e-9;
      for (const r of records) {
        const [bx, by, bz, bw] = r.ground_truth_bus_quat;
        const busNorm = Math.hypot(bx, by, bz, bw);
        expect(
          Math.abs(busNorm - 1),
          `bus quat at et=${r.et} not unit norm: |q|=${busNorm}`,
        ).toBeLessThan(TOL);
        const [px, py, pz, pw] = r.ground_truth_platform_quat;
        const platNorm = Math.hypot(px, py, pz, pw);
        expect(
          Math.abs(platNorm - 1),
          `platform quat at et=${r.et} not unit norm: |q|=${platNorm}`,
        ).toBeLessThan(TOL);
      }
    });
  },
);
