"""CK coverage inventory (SpiceyPy-based equivalent of `ckbrief`).

Writes `docs/kernels/ckbrief-inventory.md` with per-CK / per-spacecraft
coverage windows and per-encounter coverage assertions. Implements the
inventory required by Story 1.3 AC5.

Uses the SpiceyPy 8.1.0 dependency already installed via Story 1.1's
`uv sync`. Furnishes LSK + SCLK + each CK kernel in turn, then walks
`ckcov` over the Voyager bus / scan-platform / NA-camera IDs and emits
coverage intervals in UTC. Producing the same markdown twice yields
byte-identical output (no embedded host clock once the kernels are
fixed) — see test_ck_inventory.py.

Run:
    python bake/src/ck_inventory.py
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import spiceypy as spice

from _kernel_io import load_manifest, repo_root

# NAIF body / structure IDs (architecture lines 274, 719; FK files vg{1,2}_v02.tf).
# In SPICE CK files, the **structure ID** for the spacecraft bus is the
# 5-digit ID (e.g. -31000), not the 2-digit body ID (-31). The scan platform
# adds +100 (so -31100) and the NA camera +101 (-31101). The 2-digit body IDs
# (-31, -32) are SPK / ephemeris IDs.
V1_BODY = -31
V1_BUS = -31000  # CK structure ID for V1 bus (vgr1_super_v2.bc)
V1_SCAN_PLATFORM = -31100
V1_NA_CAMERA = -31101

V2_BODY = -32
V2_BUS = -32000
V2_SCAN_PLATFORM = -32100
V2_NA_CAMERA = -32101

V1_STRUCTURES = [
    ("V1 bus", V1_BUS),
    ("V1 scan platform", V1_SCAN_PLATFORM),
    ("V1 NA camera", V1_NA_CAMERA),
]
V2_STRUCTURES = [
    ("V2 bus", V2_BUS),
    ("V2 scan platform", V2_SCAN_PLATFORM),
    ("V2 NA camera", V2_NA_CAMERA),
]

# Encounter windows (UTC) per architecture / research notes.
ENCOUNTERS: list[tuple[str, str, str, int]] = [
    # (label, start_utc, end_utc, struct_id_to_check)
    ("V1 Jupiter encounter (1979-03 closest approach 03-05)", "1979-02-15T00:00:00", "1979-04-15T00:00:00", V1_SCAN_PLATFORM),
    ("V1 Saturn encounter (1980-11 closest approach 11-12)", "1980-10-15T00:00:00", "1980-12-15T00:00:00", V1_SCAN_PLATFORM),
    ("V1 Pale Blue Dot (1990-02-14 family portrait)", "1990-02-13T00:00:00", "1990-02-15T00:00:00", V1_SCAN_PLATFORM),
    ("V2 Jupiter encounter (1979-07 closest approach 07-09)", "1979-06-15T00:00:00", "1979-08-15T00:00:00", V2_SCAN_PLATFORM),
    ("V2 Saturn encounter (1981-08 closest approach 08-25)", "1981-07-15T00:00:00", "1981-09-15T00:00:00", V2_SCAN_PLATFORM),
    ("V2 Uranus encounter (1986-01 closest approach 01-24)", "1985-12-15T00:00:00", "1986-02-15T00:00:00", V2_SCAN_PLATFORM),
    ("V2 Neptune encounter (1989-08 closest approach 08-25)", "1989-07-15T00:00:00", "1989-09-15T00:00:00", V2_SCAN_PLATFORM),
]

MAX_INTERVALS = 100000  # SPICE cell size for ckcov


@dataclass(frozen=True)
class CoverageWindow:
    start_utc: str
    end_utc: str


def _utc(et: float) -> str:
    """ET seconds -> ISO-like UTC string (no Z suffix, matching ckbrief)."""
    return spice.et2utc(et, "ISOC", 3)


def _ckcov_windows(ck_path: Path, struct_id: int) -> list[CoverageWindow]:
    cover = spice.support_types.SPICEDOUBLE_CELL(MAX_INTERVALS)
    try:
        spice.ckcov(str(ck_path), struct_id, False, "INTERVAL", 0.0, "TDB", cover)
    except spice.utils.exceptions.SpiceyError:
        return []
    n = spice.wncard(cover)
    out: list[CoverageWindow] = []
    for i in range(n):
        a, b = spice.wnfetd(cover, i)
        out.append(CoverageWindow(_utc(a), _utc(b)))
    return out


def _interval_covers(window: CoverageWindow, t_start_et: float, t_end_et: float) -> bool:
    a = spice.utc2et(window.start_utc)
    b = spice.utc2et(window.end_utc)
    # Intersection check (any overlap)
    return not (b < t_start_et or a > t_end_et)


def build_inventory(root: Path) -> str:
    """Furnish kernels and build the markdown inventory string."""
    manifest_path = root / "kernels" / "kernels-manifest.json"
    _, entries = load_manifest(manifest_path)

    by_kind: dict[str, list] = {}
    for e in entries:
        by_kind.setdefault(e.kind, []).append(e)

    # Furnish order matters: LSK first, then SCLKs, then CKs.
    spice.kclear()
    for e in by_kind.get("lsk", []):
        spice.furnsh(str(root / e.target_path))
    for e in by_kind.get("sclk", []):
        spice.furnsh(str(root / e.target_path))
    ck_entries = by_kind.get("ck", [])

    spice_version = spice.tkvrsn("TOOLKIT")

    lines: list[str] = []
    lines.append("# CK Coverage Inventory")
    lines.append("")
    lines.append("Auto-generated by `bake/src/ck_inventory.py` (Story 1.3 AC5).")
    lines.append("")
    lines.append("**Reproduce:** from the repo root,")
    lines.append("")
    lines.append("    python bake/src/ck_inventory.py")
    lines.append("")
    lines.append(f"**SpiceyPy toolkit version:** {spice_version}")
    lines.append("")
    lines.append("**Voyager CK structure IDs** (verified against `ckobj` on the kernels below):")
    lines.append("")
    lines.append("| Body | CK structure ID |")
    lines.append("|------|-----------------|")
    lines.append("| V1 bus | -31000 |")
    lines.append("| V1 scan platform | -31100 |")
    lines.append("| V1 NA camera | -31101 |")
    lines.append("| V2 bus | -32000 |")
    lines.append("| V2 scan platform | -32100 |")
    lines.append("| V2 NA camera | -32101 |")
    lines.append("")
    lines.append(
        "Note: SPK body IDs (-31, -32) and CK structure IDs (-31000, -32000) differ. "
        "SPK uses the 2-digit body ID; CK uses 5-digit structure IDs offset by frame chain. "
        "The 2-digit IDs are correct for `spkez` / `spkpos`; the 5-digit IDs are correct for `ckcov` / `ckgp`."
    )
    lines.append("")

    for ck_entry in ck_entries:
        ck_path = root / ck_entry.target_path
        lines.append(f"## CK: `{ck_entry.file}`")
        lines.append("")
        lines.append(f"- **Source:** {ck_entry.attribution}")
        lines.append(f"- **Path:** `{ck_entry.target_path}`")
        lines.append(f"- **Size:** {ck_entry.size_bytes:,} bytes")
        lines.append("")

        structures = V1_STRUCTURES if "vg1" in ck_entry.file.lower() or "vgr1" in ck_entry.file.lower() else V2_STRUCTURES
        # Note: vgr1_super_v2.bc / vgr2_super_v2.bc cover the bus directly.

        any_coverage = False
        for label, sid in structures:
            windows = _ckcov_windows(ck_path, sid)
            if not windows:
                continue
            any_coverage = True
            lines.append(f"### Coverage for {label} (ID {sid})")
            lines.append("")
            lines.append(f"- Interval count: **{len(windows)}**")
            lines.append(f"- Earliest start: `{windows[0].start_utc}`")
            lines.append(f"- Latest end: `{windows[-1].end_utc}`")
            lines.append("")
            if len(windows) <= 20:
                # Continuous-ish CK: list every interval.
                lines.append("| Interval | Start (UTC) | End (UTC) |")
                lines.append("|---|---|---|")
                for i, w in enumerate(windows, start=1):
                    lines.append(f"| {i} | {w.start_utc} | {w.end_utc} |")
            else:
                # Discontinuous (e.g. PDS Rings Node ISS SEDR — one interval per image):
                # show first / last 5 only.
                lines.append("First 5 intervals:")
                lines.append("")
                lines.append("| Interval | Start (UTC) | End (UTC) |")
                lines.append("|---|---|---|")
                for i, w in enumerate(windows[:5], start=1):
                    lines.append(f"| {i} | {w.start_utc} | {w.end_utc} |")
                lines.append("")
                lines.append(f"Last 5 intervals (of {len(windows)} total):")
                lines.append("")
                lines.append("| Interval | Start (UTC) | End (UTC) |")
                lines.append("|---|---|---|")
                for i, w in enumerate(windows[-5:], start=len(windows) - 4):
                    lines.append(f"| {i} | {w.start_utc} | {w.end_utc} |")
            lines.append("")

        if not any_coverage:
            lines.append("_No coverage intervals found for any documented Voyager structure ID in this CK._")
            lines.append("")

    # Per-encounter cross-CK assertion (separate bus + scan platform columns)
    lines.append("## Encounter-window coverage cross-check")
    lines.append("")
    lines.append(
        "For each mission encounter, this table reports which CK file(s) provide coverage for "
        "(a) the spacecraft **bus** and (b) the **scan platform** during the encounter window. "
        "**Driven by FR18 / Epic 3 scoping:** scan-platform gaps are the synthesis targets for "
        "`AttitudeService` (Story 3.2)."
    )
    lines.append("")
    lines.append("| Encounter | Bus CK coverage | Scan-platform CK coverage |")
    lines.append("|---|---|---|")

    pbd_scan_status = "**NO** — synthesis required"
    pbd_bus_status = "**NO**"
    for label, t_start_utc, t_end_utc, scan_id in ENCOUNTERS:
        t_start_et = spice.utc2et(t_start_utc)
        t_end_et = spice.utc2et(t_end_utc)

        # Determine appropriate bus ID by inspecting the label
        bus_id = V1_BUS if " V1 " in f" {label} " or label.startswith("V1") else V2_BUS

        bus_covering: list[str] = []
        scan_covering: list[str] = []
        for ck_entry in ck_entries:
            ck_path = root / ck_entry.target_path
            for sid, bucket in ((bus_id, bus_covering), (scan_id, scan_covering)):
                windows = _ckcov_windows(ck_path, sid)
                for w in windows:
                    if _interval_covers(w, t_start_et, t_end_et):
                        bucket.append(ck_entry.file)
                        break

        bus_cell = ", ".join(f"`{f}`" for f in bus_covering) if bus_covering else "_(none)_"
        scan_cell = ", ".join(f"`{f}`" for f in scan_covering) if scan_covering else "**NONE — synthesize**"
        if "Pale Blue Dot" in label:
            pbd_bus_status = "YES (`vgr1_super_v2.bc` continuous)" if bus_covering else "**NO**"
            pbd_scan_status = (
                ", ".join(f"`{f}`" for f in scan_covering)
                if scan_covering
                else "**NO** — synthesis required"
            )
        lines.append(f"| {label} | {bus_cell} | {scan_cell} |")

    lines.append("")
    lines.append("## Pale Blue Dot (1990-02-14) coverage statement")
    lines.append("")
    lines.append(
        "Per Story 1.3 AC5: the explicit statement of whether the 1990-02-14 Pale Blue Dot window "
        "has CK coverage in `vgr1_super_v2.bc` (Epic 5 scoping input):"
    )
    lines.append("")
    lines.append(f"- **PBD bus-level coverage in `vgr1_super_v2.bc`:** {pbd_bus_status}")
    lines.append(f"- **PBD scan-platform coverage (any CK):** {pbd_scan_status}")
    lines.append("")
    lines.append(
        "Conclusion: the V1 super CK provides continuous bus attitude over the PBD date, but "
        "**no CK provides scan-platform attitude for the family-portrait imaging sequence**. "
        "Epic 5 (Story 5.2) will synthesize the choreographed turn-and-image attitude for the "
        "scan platform from documented mission-event sequences."
    )

    lines.append("")
    lines.append("## Synthesis gaps for HGA-Earth attitude (Epic 3 scoping)")
    lines.append("")
    lines.append(
        "Outside the encounter CK windows, **scan platform** and **HGA** attitude must be synthesized "
        "(FR18). The bus-level coverage from `vgr1_super_v2.bc` / `vgr2_super_v2.bc` does not include "
        "scan platform articulation between encounters; `AttitudeService` (Story 3.2) is responsible "
        "for the synthesized HGA-Earth-pointed cruise attitude in those gaps."
    )
    lines.append("")

    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="CK coverage inventory.")
    parser.add_argument(
        "--root",
        type=Path,
        default=None,
        help="Repo root (default: auto-detected)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output markdown path (default: <repo>/docs/kernels/ckbrief-inventory.md)",
    )
    args = parser.parse_args(argv)

    root = (args.root or repo_root()).resolve()
    out_path = (args.out or (root / "docs" / "kernels" / "ckbrief-inventory.md")).resolve()

    try:
        md = build_inventory(root)
    finally:
        spice.kclear()

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(md, encoding="utf-8")
    print(f"wrote {out_path} ({len(md)} bytes)")
    return 0


if __name__ == "__main__":
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    sys.exit(main())
