"""FK frame-ID inventory generator.

Parses `kernels/vg1_v02.tf` and `kernels/vg2_v02.tf` and writes
`kernels/frame-ids.md` (Story 1.3 Task 7, AC6).

The NAIF FK format is plain text with `FRAME_<NAME> = <ID>`,
`FRAME_<ID>_NAME = '<NAME>'`, `FRAME_<ID>_CENTER = <CENTER>`, and
TKFRAME entries for fixed-offset frames. We parse the simple key-value
form (no full PSL kernel-pool parser) since the FK files are small.

Run:
    python bake/src/fk_inventory.py
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

from _kernel_io import repo_root

FRAME_NAME_RE = re.compile(r"FRAME_(?P<name>[A-Z0-9_]+)\s*=\s*(?P<id>-?\d+)")
FRAME_CENTER_RE = re.compile(r"FRAME_(?P<id>-?\d+)_CENTER\s*=\s*(?P<center>-?\d+)")
FRAME_CLASS_RE = re.compile(r"FRAME_(?P<id>-?\d+)_CLASS\s+=\s+(?P<cls>\d+)")
TKFRAME_REL_RE = re.compile(r"TKFRAME_(?P<id>-?\d+)_RELATIVE\s*=\s*'(?P<rel>[^']+)'")
TKFRAME_ANGLES_RE = re.compile(
    r"TKFRAME_(?P<id>-?\d+)_ANGLES\s*=\s*\(\s*(?P<a>[^)]+)\)"
)
TKFRAME_AXES_RE = re.compile(
    r"TKFRAME_(?P<id>-?\d+)_AXES\s*=\s*\(\s*(?P<a>[^)]+)\)"
)
TKFRAME_UNITS_RE = re.compile(r"TKFRAME_(?P<id>-?\d+)_UNITS\s*=\s*'(?P<u>[^']+)'")


@dataclass
class FrameDef:
    name: str
    frame_id: int
    center: int | None = None
    cls: int | None = None
    relative_to: str | None = None
    angles: tuple[float, float, float] | None = None
    axes: tuple[int, int, int] | None = None
    units: str | None = None


def _parse_floats(s: str) -> tuple[float, ...]:
    parts = re.split(r"[\s,]+", s.strip())
    return tuple(float(x) for x in parts if x)


def _parse_ints(s: str) -> tuple[int, ...]:
    parts = re.split(r"[\s,]+", s.strip())
    return tuple(int(x) for x in parts if x)


def parse_fk(text: str) -> dict[int, FrameDef]:
    frames: dict[int, FrameDef] = {}

    for m in FRAME_NAME_RE.finditer(text):
        # Skip the FRAME_-31000_NAME = 'VG1_SC_BUS' form (right side is numeric
        # only when name->id; the *_NAME variants have a quoted string).
        name = m.group("name")
        if name.startswith("-"):
            continue
        # Avoid matching the FRAME_<id>_<key> sub-keys (they have additional underscores
        # after the ID like _NAME, _CLASS) — these are filtered by the regex shape
        # because we capture name+id where id is purely numeric.
        if name.endswith("_NAME") or name.endswith("_CLASS") or name.endswith("_CENTER") or name.endswith("_CLASS_ID"):
            continue
        fid = int(m.group("id"))
        frames[fid] = FrameDef(name=name, frame_id=fid)

    for m in FRAME_CENTER_RE.finditer(text):
        fid = int(m.group("id"))
        if fid in frames:
            frames[fid].center = int(m.group("center"))

    for m in FRAME_CLASS_RE.finditer(text):
        fid = int(m.group("id"))
        if fid in frames:
            frames[fid].cls = int(m.group("cls"))

    for m in TKFRAME_REL_RE.finditer(text):
        fid = int(m.group("id"))
        if fid in frames:
            frames[fid].relative_to = m.group("rel")

    for m in TKFRAME_ANGLES_RE.finditer(text):
        fid = int(m.group("id"))
        if fid in frames:
            vals = _parse_floats(m.group("a"))
            if len(vals) == 3:
                frames[fid].angles = vals  # type: ignore[assignment]

    for m in TKFRAME_AXES_RE.finditer(text):
        fid = int(m.group("id"))
        if fid in frames:
            vals = _parse_ints(m.group("a"))
            if len(vals) == 3:
                frames[fid].axes = vals  # type: ignore[assignment]

    for m in TKFRAME_UNITS_RE.finditer(text):
        fid = int(m.group("id"))
        if fid in frames:
            frames[fid].units = m.group("u")

    return frames


def build_markdown(root: Path) -> str:
    fk1 = (root / "kernels" / "vg1_v02.tf").read_text(encoding="utf-8", errors="replace")
    fk2 = (root / "kernels" / "vg2_v02.tf").read_text(encoding="utf-8", errors="replace")
    frames1 = parse_fk(fk1)
    frames2 = parse_fk(fk2)

    lines: list[str] = []
    lines.append("# Voyager FK Frame IDs")
    lines.append("")
    lines.append(
        "Auto-generated by `bake/src/fk_inventory.py` (Story 1.3 AC6). "
        "Reads `kernels/vg1_v02.tf` and `kernels/vg2_v02.tf` (both NAIF FKs) "
        "and emits the documented FRAME / TKFRAME entries that Stories 1.5+ "
        "rendering and Story 3.2 HGA-Earth synthesis depend on (per technical-research "
        "line 1531)."
    )
    lines.append("")
    lines.append("**Reproduce:** from the repo root,")
    lines.append("")
    lines.append("    python bake/src/fk_inventory.py")
    lines.append("")
    lines.append(
        "## Frame ID conventions\n\n"
        "Voyager NAIF frame IDs follow a `-3X000` pattern where `X` is `1` for "
        "Voyager 1 and `2` for Voyager 2. The 2-digit spacecraft body IDs (`-31` / `-32`) "
        "are SPK ephemeris IDs and are NOT frame IDs.\n\n"
        "| Subsystem | V1 frame ID | V2 frame ID | Parent / class |\n"
        "|---|---|---|---|\n"
        "| Spacecraft bus | -31000 | -32000 | CK class 3 (inertial via CK) |\n"
        "| Scan platform | -31100 | -32100 | CK class 3 (inertial via CK) |\n"
        "| NA camera (ISSNA) | -31101 | -32101 | TK class 4 — relative to SCAN_PLATFORM |\n"
        "| WA camera (ISSWA) | -31102 | -32102 | TK class 4 — relative to SCAN_PLATFORM |\n"
        "| PPS | -31103 | -32103 | TK class 4 — relative to SCAN_PLATFORM |\n"
        "| UVS | -31104 | -32104 | TK class 4 — relative to SCAN_PLATFORM |\n"
        "| UVSOCC | -31105 | -32105 | TK class 4 — relative to SCAN_PLATFORM |\n"
        "| IRIS | -31106 | -32106 | TK class 4 — relative to SCAN_PLATFORM |\n"
        "| IRISOCC | -31107 | -32107 | TK class 4 — relative to SCAN_PLATFORM |\n"
        "| CONE_CLOCK | -31200 | -32200 | TK class 4 — relative to SC_BUS |\n"
        "| AZ_EL | -31300 | -32300 | TK class 4 — relative to SC_BUS |\n"
        "| **HGA** | **-31400** | **-32400** | TK class 4 — relative to SC_BUS (boresight +Z) |\n"
    )
    lines.append("")
    lines.append(
        "**Note on Story 3.2 / FR18:** the HGA frames are fixed offsets relative to the "
        "spacecraft bus (`VG1_SC_BUS` / `VG2_SC_BUS`). When the bus attitude is provided "
        "by `vgr{1,2}_super_v2.bc` (CK class 3), the HGA boresight in inertial coordinates is "
        "fully determined. AttitudeService can use the +Z axis of the HGA frame as the "
        "HGA-Earth pointing reference."
    )
    lines.append("")

    for label, frames in (("Voyager 1 (`vg1_v02.tf`)", frames1), ("Voyager 2 (`vg2_v02.tf`)", frames2)):
        lines.append(f"## {label}")
        lines.append("")
        lines.append("| Frame name | Frame ID | Class | Center | Relative to | Angles (deg) | Axes |")
        lines.append("|---|---|---|---|---|---|---|")
        for fid in sorted(frames.keys()):
            f = frames[fid]
            angles_str = (
                f"({f.angles[0]}, {f.angles[1]}, {f.angles[2]})"
                if f.angles is not None
                else "—"
            )
            axes_str = (
                f"({f.axes[0]}, {f.axes[1]}, {f.axes[2]})"
                if f.axes is not None
                else "—"
            )
            lines.append(
                f"| `{f.name}` | {f.frame_id} | {f.cls if f.cls is not None else '—'} | "
                f"{f.center if f.center is not None else '—'} | "
                f"{f.relative_to or '—'} | {angles_str} | {axes_str} |"
            )
        lines.append("")

    lines.append("## Provenance")
    lines.append("")
    lines.append(
        "Generated from the FK files committed under `kernels/`. The FK files are "
        "themselves SHA-256-pinned in `kernels/kernels-manifest.json` (see Story 1.3 AC2)."
    )
    lines.append("")

    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="FK frame-ID inventory.")
    parser.add_argument(
        "--root",
        type=Path,
        default=None,
        help="Repo root (default: auto-detected)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output markdown path (default: <repo>/kernels/frame-ids.md)",
    )
    args = parser.parse_args(argv)

    root = (args.root or repo_root()).resolve()
    out_path = (args.out or (root / "kernels" / "frame-ids.md")).resolve()
    md = build_markdown(root)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(md, encoding="utf-8")
    print(f"wrote {out_path} ({len(md)} bytes)")
    return 0


if __name__ == "__main__":
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    sys.exit(main())
