"""Regenerate ``docs/adr/README.md`` as a table-of-contents for the ADR catalogue.

This script is the canonical implementation of ``just adr-index`` (the justfile recipe
will be introduced by Story 1.4). For now, invoke as::

    python scripts/adr-index.py

The script is deterministic: running it twice on the same inputs produces byte-identical
output. The catalogue completeness test at ``bake/tests/test_adr_catalogue.py`` asserts
that the index covers every ADR file and that ADR section headers are well-formed.

ADR storage convention (ADR 0020):

* ``docs/adr/NNNN-kebab-case-title.md`` where ``NNNN`` is a 4-digit zero-padded sequence
* ``docs/adr/0000-template.md`` is the canonical template (included as row 0 in the index)
* ``docs/adr/README.md`` is auto-generated by this script; do not hand-edit
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ADR_DIR = REPO_ROOT / "docs" / "adr"
INDEX_FILE = ADR_DIR / "README.md"

ADR_FILENAME_PATTERN = re.compile(r"^(\d{4})-[a-z0-9][a-z0-9-]*\.md$")
H1_PATTERN = re.compile(r"^#\s+(.+?)\s*$")
STATUS_PATTERN = re.compile(r"^Status:\s*(.+?)\s*$")

GENERATED_HEADER = """<!-- AUTO-GENERATED FILE — do not hand-edit.
     Regenerate with: python scripts/adr-index.py
     Source: docs/adr/[0-9][0-9][0-9][0-9]-*.md
     See ADR 0020 for the catalogue policy. -->

# Architectural Decision Records

This directory contains the Voyager project's Architectural Decision Records (ADRs).
Format: MADR minimal 5-section variant ([ADR 0020](0020-madr-format-for-adrs-docs-adr-location.md)).
New ADRs use the template at [`0000-template.md`](0000-template.md).
"""

INDEX_TABLE_HEADER = """| # | Title | Status | Path |
| --- | --- | --- | --- |
"""


def parse_adr(path: Path) -> tuple[str, str]:
    """Return (title, status) for the ADR at ``path``.

    The H1 title is the first ``# ``-prefixed line. The status is the first
    ``Status:``-prefixed line. Either may legitimately be missing on the template
    (where the title is ``# ADR NNNN — <Title>``); we use whatever the file contains.
    """
    title = ""
    status = ""
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            if not title:
                match = H1_PATTERN.match(line)
                if match:
                    title = match.group(1)
                    continue
            if not status:
                match = STATUS_PATTERN.match(line)
                if match:
                    status = match.group(1)
            if title and status:
                break
    return title, status


def collect_adrs() -> list[tuple[int, str, str, Path]]:
    """Return a sorted list of ``(number, title, status, path)`` tuples.

    Sorted by the 4-digit number prefix. Includes ``0000-template.md`` as row 0.
    """
    entries: list[tuple[int, str, str, Path]] = []
    for path in sorted(ADR_DIR.glob("[0-9][0-9][0-9][0-9]-*.md")):
        match = ADR_FILENAME_PATTERN.match(path.name)
        if not match:
            continue
        number = int(match.group(1))
        title, status = parse_adr(path)
        entries.append((number, title, status, path))
    entries.sort(key=lambda entry: entry[0])
    return entries


def render_index(entries: list[tuple[int, str, str, Path]]) -> str:
    """Render the index Markdown content from the collected ADR entries."""
    rows: list[str] = []
    for number, title, status, path in entries:
        rel = path.name
        title_cell = title or "(untitled)"
        status_cell = status or "(unknown)"
        rows.append(f"| {number:04d} | [{title_cell}]({rel}) | {status_cell} | `docs/adr/{rel}` |")
    table = INDEX_TABLE_HEADER + "\n".join(rows) + "\n"
    return GENERATED_HEADER + "\n" + table


def main() -> int:
    if not ADR_DIR.is_dir():
        print(f"error: {ADR_DIR} does not exist", file=sys.stderr)
        return 1
    entries = collect_adrs()
    if not entries:
        print(f"error: no ADR files matching [0-9][0-9][0-9][0-9]-*.md in {ADR_DIR}", file=sys.stderr)
        return 1
    content = render_index(entries)
    INDEX_FILE.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {INDEX_FILE} ({len(entries)} ADR entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
