"""Story 1.3 CK inventory tests (AC5).

The inventory generator (`bake/src/ck_inventory.py`) is a small wrapper around
SpiceyPy that reads the real kernels. These tests:

* Assert the on-disk `docs/kernels/ckbrief-inventory.md` has the expected
  structure (header + per-CK sections + encounter-window cross-check + PBD
  statement + synthesis-gaps section).
* Assert the PBD line is present in some form (AC5 explicit-statement rule).
* Assert determinism: regenerating the inventory in-place produces a
  byte-identical file (Task 8 requirement). Skipped if SpiceyPy is not
  importable.
"""

from __future__ import annotations

import hashlib
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
INVENTORY_PATH = REPO_ROOT / "docs" / "kernels" / "ckbrief-inventory.md"
CK_INVENTORY_SCRIPT = REPO_ROOT / "bake" / "src" / "ck_inventory.py"
FRAME_IDS_PATH = REPO_ROOT / "kernels" / "frame-ids.md"
FK_INVENTORY_SCRIPT = REPO_ROOT / "bake" / "src" / "fk_inventory.py"


def test_inventory_file_exists() -> None:
    assert INVENTORY_PATH.exists(), (
        f"Inventory not found at {INVENTORY_PATH}. "
        "Run: python bake/src/ck_inventory.py from the repo root."
    )


def test_inventory_has_header_and_reproduction_command() -> None:
    text = INVENTORY_PATH.read_text(encoding="utf-8")
    assert "# CK Coverage Inventory" in text
    assert "Auto-generated by `bake/src/ck_inventory.py`" in text
    assert "python bake/src/ck_inventory.py" in text, (
        "AC5 header must document the reproduction command"
    )
    assert "SpiceyPy toolkit version" in text


def test_inventory_lists_all_seven_voyager_ck_kernels() -> None:
    text = INVENTORY_PATH.read_text(encoding="utf-8")
    for expected_ck in [
        "vgr1_super_v2.bc",
        "vgr2_super_v2.bc",
        "vg1_jup_version1_type1_iss_sedr.bc",
        "vg2_jup_version1_type1_iss_sedr.bc",
        "vg1_sat_version1_type1_iss_sedr.bc",
        "vg2_sat_version1_type1_iss_sedr.bc",
        "vg2_ura_version1_type1_iss_sedr.bc",
        "vg2_nep_version1_type1_iss_sedr.bc",
    ]:
        assert f"## CK: `{expected_ck}`" in text or expected_ck in text, (
            f"Inventory must document CK file {expected_ck}"
        )


@pytest.mark.parametrize(
    "encounter_substring",
    [
        "V1 Jupiter encounter",
        "V1 Saturn encounter",
        "Pale Blue Dot",
        "V2 Jupiter encounter",
        "V2 Saturn encounter",
        "V2 Uranus encounter",
        "V2 Neptune encounter",
    ],
)
def test_inventory_documents_each_encounter_window(encounter_substring: str) -> None:
    """AC5: every required encounter window must be named in the cross-check."""
    text = INVENTORY_PATH.read_text(encoding="utf-8")
    assert encounter_substring in text, (
        f"AC5 requires explicit encounter window assertion for: {encounter_substring}"
    )


def test_inventory_has_pbd_coverage_statement() -> None:
    """AC5 explicit-statement rule: PBD coverage MUST be addressed in some form."""
    text = INVENTORY_PATH.read_text(encoding="utf-8")
    assert "1990-02-14" in text, "PBD date must appear (Epic 5 scoping input)"
    assert "Pale Blue Dot" in text
    assert "PBD coverage" in text or "PBD bus-level" in text or "PBD scan-platform" in text


def test_inventory_documents_synthesis_gaps() -> None:
    """AC5: synthesis gaps (for HGA-Earth, Epic 3 scoping) must be documented."""
    text = INVENTORY_PATH.read_text(encoding="utf-8")
    assert "synthes" in text.lower(), "Synthesis gaps must be documented (FR18 / Story 3.2)"
    # The HGA reference is the Story 3.2 motivator.
    assert "HGA" in text


def test_inventory_regeneration_is_byte_identical() -> None:
    """Determinism: re-running ck_inventory.py produces byte-identical output.

    Skipped if spiceypy or the kernels aren't available in this environment.
    """
    try:
        import spiceypy  # noqa: F401
    except ImportError:
        pytest.skip("spiceypy not importable — skipping determinism test")

    if not INVENTORY_PATH.exists():
        pytest.skip("inventory file not present")

    before = INVENTORY_PATH.read_bytes()
    before_sha = hashlib.sha256(before).hexdigest()

    res = subprocess.run(
        [sys.executable, str(CK_INVENTORY_SCRIPT)],
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
        check=False,
    )
    assert res.returncode == 0, f"ck_inventory.py failed: {res.stderr}"

    after = INVENTORY_PATH.read_bytes()
    after_sha = hashlib.sha256(after).hexdigest()
    assert before_sha == after_sha, (
        f"ck_inventory.py is not deterministic:\n"
        f"  before SHA: {before_sha}\n  after SHA: {after_sha}"
    )


def test_frame_ids_doc_exists_with_v1_and_v2_sections() -> None:
    """AC6: kernels/frame-ids.md must exist and document V1 + V2 frames."""
    assert FRAME_IDS_PATH.exists(), f"frame-ids.md missing at {FRAME_IDS_PATH}"
    text = FRAME_IDS_PATH.read_text(encoding="utf-8")
    assert "# Voyager FK Frame IDs" in text
    # Required frames per AC6: V1 bus, V1 scan platform, V1 NA camera, V1 HGA + same for V2.
    for frame_id in ("-31000", "-31100", "-31101", "-31400", "-32000", "-32100", "-32101", "-32400"):
        assert frame_id in text, f"frame-ids.md missing required frame ID {frame_id}"
    for symbol in ("VG1_SC_BUS", "VG1_SCAN_PLATFORM", "VG1_HGA", "VG2_SC_BUS", "VG2_SCAN_PLATFORM", "VG2_HGA"):
        assert symbol in text, f"frame-ids.md missing required frame name {symbol}"


def test_frame_ids_doc_is_deterministic() -> None:
    """Determinism: re-running fk_inventory.py produces byte-identical output."""
    if not FRAME_IDS_PATH.exists():
        pytest.skip("frame-ids.md not present")
    before = FRAME_IDS_PATH.read_bytes()
    before_sha = hashlib.sha256(before).hexdigest()

    res = subprocess.run(
        [sys.executable, str(FK_INVENTORY_SCRIPT)],
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
        check=False,
    )
    assert res.returncode == 0, f"fk_inventory.py failed: {res.stderr}"

    after = FRAME_IDS_PATH.read_bytes()
    after_sha = hashlib.sha256(after).hexdigest()
    assert before_sha == after_sha, "fk_inventory.py output should be deterministic"
